add infos on recent games link and style for focused games
Judas/go-ladder-for-discord-website pull request #5
Opened 2023-10-14 17:22 UTC by Kirwiisp

Add Players name in the link tag to clarify context for screen reader ( preventing multiple "Voir partie" when getting the links on the page).
Add border on the focused game card

2023-11-08 11:11 UTC, Judas requested changes

2023-11-08 11:11 UTC, Judas commented on src/Pages/RecentGames.css
> +	outline-offset: 0.25em;
Indente avec des espaces plutôt.

2023-11-08 11:11 UTC, Judas commented on src/Pages/RecentGames.jsx
> +        		{game.black.name} versus {game.white.name} Voir la partie
Je mettrais plutôt `Voir {game.black.name} versus {game.white.name}`

2023-11-09 06:57 UTC, Kirwiisp commented on src/Pages/RecentGames.jsx
> +        		{game.black.name} versus {game.white.name} Voir la partie
c'est fait !

2024-10-11 13:21 UTC, closed without merging